export const FETCH_GISTS = 'FETCH_GISTS';
export const FETCH_GISTS_PENDING = 'FETCH_GISTS_PENDING';
export const FETCH_GISTS_FULFILLED = 'FETCH_GISTS_FULFILLED';
export const FETCH_GISTS_REJECTED = 'FETCH_GISTS_REJECTED';


export const FETCH_GIST_DETAILS = 'FETCH_GIST_DETAILS';
export const FETCH_GIST_DETAILS_PENDING = 'FETCH_GIST_DETAILS_PENDING';
export const FETCH_GIST_DETAILS_FULFILLED = 'FETCH_GIST_DETAILS_FULFILLED';
export const FETCH_GIST_DETAILS_REJECTED = 'FETCH_GIST_DETAILS_REJECTED';